name: synthoct-py312
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy=1.26.4
  - scipy=1.13.1
  - numba=0.60.0
  - scikit-image=0.24.0
  - matplotlib=3.9.2
  - pytest
  - pip:
      - sewar==0.4.6
      - -e .
