from __future__ import annotations

import csv
import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np
from scipy.ndimage import gaussian_filter
from skimage.transform import resize

from .features import calculate_oac, calculate_speckle_contrast_map, load_and_linearize_image, load_scan
from .learned_surrogate import field_to_phantom, phantom_to_field
from .phantom import ExperimentConfig


TRUE_SCANNER_SOURCES = {"hosted_api_true_scanner", "official_windows_true_scanner"}
NEURAL_PRIOR_METHODS = ("neural-prior",)
HYBRID_PRIOR_CONFIGS: dict[str, dict[str, float]] = {
    "hybrid-neural-p140-t32-b05": {"neural_density_blend": 0.05},
    "hybrid-neural-p140-t32-b10": {"neural_density_blend": 0.10},
    "hybrid-neural-p140-t32-b15": {"neural_density_blend": 0.15},
    "hybrid-neural-p140-t32-b20": {"neural_density_blend": 0.20},
    "hybrid-neural-p140-t32-e05": {"neural_density_blend": 0.0, "neural_energy_blend": 0.05},
    "hybrid-neural-p140-t32-e10": {"neural_density_blend": 0.0, "neural_energy_blend": 0.10},
    "hybrid-neural-p140-t32-e20": {"neural_density_blend": 0.0, "neural_energy_blend": 0.20},
    "hybrid-neural-p140-t32-e30": {"neural_density_blend": 0.0, "neural_energy_blend": 0.30},
    "hybrid-neural-p140-t32-e40": {"neural_density_blend": 0.0, "neural_energy_blend": 0.40},
    "hybrid-neural-p140-t32-e60": {"neural_density_blend": 0.0, "neural_energy_blend": 0.60},
}
HYBRID_PRIOR_METHODS = tuple(HYBRID_PRIOR_CONFIGS.keys())


@dataclass(frozen=True)
class NeuralTrainingPair:
    label: str
    reference_path: Path
    phantom_path: Path
    rendered_gray_path: Path
    score: float


def discover_neural_training_pairs(outputs_dir: str | Path = "outputs", limit: int = 128) -> list[NeuralTrainingPair]:
    """Collect true-scanner rows that connect a reference scan to a generated phantom.

    The rows are training material for a model artifact, not challenge evidence
    for the artifact itself. Promotion still requires true-scanner validation of
    phantoms generated by the trained model.
    """
    pairs: dict[Path, NeuralTrainingPair] = {}
    outputs_dir = Path(outputs_dir)
    csv_paths = sorted(set(outputs_dir.glob("**/*metrics*.csv")) | set(outputs_dir.glob("**/*validation_detail.csv")))
    for metrics_path in csv_paths:
        try:
            rows = list(csv.DictReader(metrics_path.open()))
        except Exception:
            continue
        for row in rows:
            source = str(row.get("evidence_source", ""))
            if source and source not in TRUE_SCANNER_SOURCES:
                continue
            reference = row.get("reference_png", "")
            phantom = row.get("phantom_path", "")
            rendered = row.get("synthetic_gray_png", "") or row.get("true_scanner_render_png", "")
            if not reference or not phantom or not rendered:
                continue
            reference_path = Path(reference)
            phantom_path = Path(phantom)
            rendered_path = Path(rendered)
            if not reference_path.exists() or not phantom_path.exists() or not rendered_path.exists():
                continue
            score = _row_quality_score(row)
            if not np.isfinite(score):
                continue
            pairs[phantom_path.resolve()] = NeuralTrainingPair(
                label=str(row.get("method") or row.get("label") or metrics_path.stem),
                reference_path=reference_path.resolve(),
                phantom_path=phantom_path.resolve(),
                rendered_gray_path=rendered_path.resolve(),
                score=float(score),
            )
    return sorted(pairs.values(), key=lambda pair: pair.score, reverse=True)[:limit]


def train_neural_phantom_prior(
    outputs_dir: str | Path,
    out_path: str | Path,
    *,
    shape: tuple[int, int] = (128, 256),
    pair_limit: int = 128,
    epochs: int = 80,
    learning_rate: float = 2e-3,
    seed: int = 37,
) -> Path:
    """Train a small CNN that maps reference-scan features to phantom fields."""
    try:
        import torch
    except Exception as exc:  # pragma: no cover - optional dependency.
        raise RuntimeError("Training a neural phantom prior requires torch.") from exc

    torch.manual_seed(seed)
    np.random.seed(seed)
    pairs = discover_neural_training_pairs(outputs_dir, limit=pair_limit)
    if not pairs:
        raise RuntimeError(f"No true-scanner reference/phantom training rows found under {outputs_dir}.")

    x_np = np.stack([reference_feature_stack(pair.reference_path, shape=shape) for pair in pairs], axis=0)
    y_np = np.stack([phantom_to_field(pair.phantom_path, shape=shape) for pair in pairs], axis=0)
    scores = np.array([pair.score for pair in pairs], dtype=np.float32)
    weights = _training_weights(scores)

    device = torch.device("cpu")
    x = torch.from_numpy(x_np.astype(np.float32)).to(device)
    y = torch.from_numpy(y_np.astype(np.float32)).to(device)
    w = torch.from_numpy(weights.astype(np.float32)).to(device).view(-1, 1, 1, 1)

    model = _NeuralPhantomFieldNet().to(device)
    opt = torch.optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=1e-4)
    for _epoch in range(max(1, epochs)):
        pred = model(x)
        loss = ((pred - y).abs() * w).mean() + 0.12 * _gradient_loss(pred, y)
        opt.zero_grad()
        loss.backward()
        opt.step()

    with torch.no_grad():
        final_loss = float(((model(x) - y).abs() * w).mean().cpu().item())

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    artifact = {
        "model_state": model.state_dict(),
        "model_name": "NeuralPhantomFieldNet",
        "input_channels": ["struct", "detail", "oac", "speckle"],
        "output_channels": ["density", "energy", "mean_energy", "cumulative_energy"],
        "shape": tuple(int(v) for v in shape),
        "pair_count": len(pairs),
        "labels": [pair.label for pair in pairs],
        "scores": [float(pair.score) for pair in pairs],
        "reference_paths": [str(pair.reference_path) for pair in pairs],
        "phantom_paths": [str(pair.phantom_path) for pair in pairs],
        "rendered_gray_paths": [str(pair.rendered_gray_path) for pair in pairs],
        "final_training_l1": final_loss,
        "evidence_source": "neural_phantom_prior_model",
        "evidence_scope": "not_challenge_evidence",
        "interpretation": (
            "Scanner-compatible neural phantom-field generator artifact. "
            "Generated phantoms must be rendered by the true scanner before promotion."
        ),
    }
    torch.save(artifact, out_path)
    metadata_path = out_path.with_suffix(".json")
    metadata = {key: value for key, value in artifact.items() if key != "model_state"}
    metadata_path.write_text(json.dumps(metadata, indent=2, sort_keys=True), encoding="utf-8")
    return out_path


def neural_prior_phantom(
    input_path: str | Path,
    output_path: str | Path,
    artifact_path: str | Path,
    *,
    seed: int = 7,
    scatterers_count: int = 300_000,
    density_power: float = 1.0,
    target_detail_blend: float = 0.10,
    energy_floor: float = 0.002,
    energy_ceiling: float = 0.075,
) -> Path:
    """Generate a challenge-format phantom from a trained neural prior artifact."""
    density, energy = neural_prior_fields(
        input_path,
        artifact_path,
        shape=(ExperimentConfig().n_depth, ExperimentConfig().n_lateral),
        density_power=density_power,
        target_detail_blend=target_detail_blend,
    )
    return field_to_phantom(
        density,
        energy,
        output_path,
        scatterers_count=scatterers_count,
        seed=seed,
        energy_floor=energy_floor,
        energy_ceiling=energy_ceiling,
    )


def neural_prior_fields(
    input_path: str | Path,
    artifact_path: str | Path,
    *,
    shape: tuple[int, int],
    density_power: float = 1.0,
    target_detail_blend: float = 0.10,
) -> tuple[np.ndarray, np.ndarray]:
    """Predict normalized density and energy fields from a trained neural artifact."""
    try:
        import torch
    except Exception as exc:  # pragma: no cover - optional dependency.
        raise RuntimeError("Generating from a neural phantom prior requires torch.") from exc

    artifact = torch.load(artifact_path, map_location="cpu", weights_only=False)
    model = _NeuralPhantomFieldNet()
    model.load_state_dict(artifact["model_state"])
    model.eval()

    features = reference_feature_stack(input_path, shape=shape)
    with torch.no_grad():
        pred = model(torch.from_numpy(features[None].astype(np.float32))).cpu().numpy()[0]

    target_detail = features[1]
    density = np.maximum(pred[0], 1e-8)
    if target_detail_blend:
        blend = float(np.clip(target_detail_blend, 0.0, 1.0))
        density = (1.0 - blend) * density + blend * _normalize(target_detail, floor=1e-8)
    density = np.maximum(density, 1e-8) ** max(0.05, density_power)
    energy = _normalize(pred[1], floor=1e-5)
    return density, energy


def reference_feature_stack(path: str | Path, *, shape: tuple[int, int]) -> np.ndarray:
    """Build neural input channels from a reference OCT B-scan."""
    image = _resize01(load_scan(path), shape, sigma=(0.8, 1.4))
    linear = load_and_linearize_image(path)
    oac = calculate_oac(linear)
    speckle = calculate_speckle_contrast_map(linear)
    detail = np.maximum(load_scan(path) - gaussian_filter(load_scan(path), sigma=(0.8, 1.2)), 0.0)
    channels = [
        _normalize(image, floor=0.0),
        _normalize(_resize01(detail, shape, sigma=0.4), floor=0.0),
        _normalize(_resize01(oac, shape, sigma=(0.5, 1.0)), floor=0.0),
        _normalize(_resize01(speckle, shape, sigma=0.8), floor=0.0),
    ]
    return np.stack(channels, axis=0).astype(np.float32)


def _row_quality_score(row: dict[str, str]) -> float:
    struct_ms = _finite(row.get("Struct_MS-SSIM"))
    struct_lpips = _finite(row.get("Struct_LPIPS"))
    if np.isfinite(struct_ms) and np.isfinite(struct_lpips):
        return float(struct_ms - struct_lpips)
    ms = _finite(row.get("MS-SSIM") or row.get("MS-SSIM_mean"))
    lpips = _finite(row.get("LPIPS") or row.get("LPIPS_or_proxy_mean"))
    if np.isfinite(ms) and np.isfinite(lpips):
        return float(ms - lpips)
    ssim = _finite(row.get("Struct_SSIM") or row.get("SSIM"))
    return float(ssim)


def _finite(value: str | float | None) -> float:
    try:
        out = float(value)  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return float("nan")
    return out if np.isfinite(out) else float("nan")


def _training_weights(scores: np.ndarray) -> np.ndarray:
    if scores.size == 0:
        return scores
    centered = scores - np.nanmax(scores)
    weights = np.exp(centered / 0.08)
    if not np.isfinite(weights).all() or weights.sum() <= 0:
        weights = np.ones_like(scores)
    weights = weights / weights.mean()
    return np.clip(weights, 0.35, 2.0).astype(np.float32)


def _resize01(arr: np.ndarray, shape: tuple[int, int], sigma: float | tuple[float, float] = 0.0) -> np.ndarray:
    arr = np.asarray(arr, dtype=np.float32)
    if np.any(np.asarray(sigma, dtype=float) > 0):
        arr = gaussian_filter(arr, sigma=sigma)
    return np.asarray(resize(arr, shape, anti_aliasing=True, preserve_range=True), dtype=np.float32)


def _normalize(arr: np.ndarray, floor: float = 0.0) -> np.ndarray:
    arr = np.asarray(arr, dtype=np.float32)
    arr = arr - np.nanmin(arr)
    peak = float(np.nanmax(arr))
    if peak > 1e-8:
        arr = arr / peak
    return np.maximum(arr, floor).astype(np.float32)


def _gradient_loss(pred, target):
    return (pred[:, :, 1:, :] - target[:, :, 1:, :]).abs().mean() + (pred[:, :, :, 1:] - target[:, :, :, 1:]).abs().mean()


class _NeuralPhantomFieldNet:
    def __new__(cls):
        from torch import nn

        return nn.Sequential(
            nn.Conv2d(4, 24, kernel_size=5, padding=2),
            nn.GELU(),
            nn.Conv2d(24, 32, kernel_size=5, padding=2),
            nn.GELU(),
            nn.Conv2d(32, 24, kernel_size=3, padding=1),
            nn.GELU(),
            nn.Conv2d(24, 4, kernel_size=1),
            nn.Sigmoid(),
        )
